x-common-env: &common-env
  FUZZ_RUNS: ${FUZZ_RUNS}
  FUZZ_INPUT: ${FUZZ_INPUT}

services:
  script:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DRUST_BITCOIN"
      FUZZ: script
    volumes:
      - ./docker/script:/app/data

  deserialize_block:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD"
      FUZZ: deserialize_block
    volumes:
      - ./docker/deserialize_block:/app/data

  script_eval:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DBTCD"
      FUZZ: script_eval
    volumes:
      - ./docker/script_eval:/app/data

  descriptor_parse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DNBITCOIN -DRUST_MINISCRIPT -DEMBIT"
      FUZZ: descriptor_parse
      ASAN_OPTIONS: detect_leaks=0
    volumes:
      - ./docker/descriptor_parse:/app/data

  miniscript_parse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DNBITCOIN -DRUST_MINISCRIPT -DEMBIT"
      FUZZ: miniscript_parse
      ASAN_OPTIONS: detect_leaks=0
    volumes:
      - ./docker/miniscript_parse:/app/data

  script_asm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DBTCD"
      FUZZ: script_asm
    volumes:
      - ./docker/script_asm:/app/data

  deserialize_invoice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DLDK -DLND -DNLIGHTNING -DCLIGHTNING -DECLAIR -DLIGHTNING_KMP -DCUSTOM_MUTATOR_BOLT11"
      FUZZ: deserialize_invoice
      ASAN_OPTIONS: detect_leaks=0
    volumes:
      - ./docker/deserialize_invoice:/app/data

  address_parse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DRUST_BITCOIN"
      FUZZ: address_parse
    volumes:
      - ./docker/address_parse:/app/data

  addrv2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD"
      FUZZ: addrv2
    volumes:
      - ./docker/addrv2:/app/data

  transaction_eval:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DBTCD"
      FUZZ: transaction_eval
    volumes:
      - ./docker/transaction_eval:/app/data

  parse_p2p_message:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DRUST_BITCOIN -DBTCD -DCUSTOM_MUTATOR_P2P_MESSAGE"
      FUZZ: parse_p2p_message
    volumes:
      - ./docker/parse_p2p_message:/app/data

  psbt_parse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DEMBIT -DRUST_BITCOIN -DBTCD -DBITCOIN_CORE"
      FUZZ: psbt_parse
      ASAN_OPTIONS: detect_leaks=0
    volumes:
      - ./docker/psbt_parse:/app/data

  deserialize_offer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DLDK -DCLIGHTNING -DECLAIR -DCUSTOM_MUTATOR_BOLT12_OFFER"
      FUZZ: deserialize_offer
    volumes:
      - ./docker/deserialize_offer:/app/data

  parse_p2p_lightning_message:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DLDK -DCLIGHTNING -DLND"
      FUZZ: parse_p2p_lightning_message
    volumes:
      - ./docker/parse_p2p_lightning_message:/app/data

  bip32_deserialize_key_xpub_xprv:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      CXXFLAGS: "-DBITCOIN_CORE -DRUST_BITCOIN -DNBITCOIN"
      FUZZ: bip32_deserialize_key_xpub_xprv
      ASAN_OPTIONS: detect_leaks=0
    volumes:
      - ./docker/bip32_deserialize_key_xpub_xprv:/app/data