// Static build info header for bitcoinfuzz builds.
// Normally generated by cmake/script/GenerateBuildInfo.cmake.
// Leaving BUILD_GIT_TAG and BUILD_GIT_COMMIT undefined results in a "-unk" version suffix.
